/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Amex: typeof import('./src/components/CreditCard/icons/Amex.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Back: typeof import('./src/components/CreditCard/cards/Back.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CreditCard: typeof import('./src/components/CreditCard.vue')['default']
    Diners: typeof import('./src/components/CreditCard/icons/Diners.vue')['default']
    Discover: typeof import('./src/components/CreditCard/icons/Discover.vue')['default']
    Front: typeof import('./src/components/CreditCard/cards/Front.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Jcb: typeof import('./src/components/CreditCard/icons/Jcb.vue')['default']
    Login: typeof import('./src/pages/Login.vue')['default']
    Maestro: typeof import('./src/components/CreditCard/icons/Maestro.vue')['default']
    Mastercard: typeof import('./src/components/CreditCard/icons/Mastercard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Unipay: typeof import('./src/components/CreditCard/icons/Unipay.vue')['default']
    Visa: typeof import('./src/components/CreditCard/icons/Visa.vue')['default']
  }
}
