/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/cambiarContrasena': RouteRecordInfo<'/cambiarContrasena', '/cambiarContrasena', Record<never, never>, Record<never, never>>,
    '/datosPersonales': RouteRecordInfo<'/datosPersonales', '/datosPersonales', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/ingresar': RouteRecordInfo<'/ingresar', '/ingresar', Record<never, never>, Record<never, never>>,
    '/linkDePago': RouteRecordInfo<'/linkDePago', '/linkDePago', Record<never, never>, Record<never, never>>,
    '/movimientos': RouteRecordInfo<'/movimientos', '/movimientos', Record<never, never>, Record<never, never>>,
    '/pago/[uuid]': RouteRecordInfo<'/pago/[uuid]', '/pago/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    '/registrar': RouteRecordInfo<'/registrar', '/registrar', Record<never, never>, Record<never, never>>,
    '/solicitarReset': RouteRecordInfo<'/solicitarReset', '/solicitarReset', Record<never, never>, Record<never, never>>,
    '/tarjetas': RouteRecordInfo<'/tarjetas', '/tarjetas', Record<never, never>, Record<never, never>>,
    '/transferir': RouteRecordInfo<'/transferir', '/transferir', Record<never, never>, Record<never, never>>,
    '/verificar': RouteRecordInfo<'/verificar', '/verificar', Record<never, never>, Record<never, never>>,
  }
}
